### ISSUE TITLE
Is QC_Impacts_Analysis_singleseed_cb.R the same as QC_Impacts_Analysis_singleseed.R?

### ISSUE THREAD

**Issue by mbnebel** [thebrisklab/DeconfoundedFMRI#8]
@BenjaminRisk It looks like [QC_Impacts_loopSeeds.sh](https://github.com/thebrisklab/DeconfoundedFMRI/blob/main/QC_Impacts_loopSeeds.sh) uses QC_Impacts_Analysis_singleseed.R, but I only see QC_Impacts_Analysis_singleseed_cb.R in the repository. Could you explain how you used the bash and R scripts to repeat the entire DRTMLE procedure for 400 initial random seeds?

**Comment by BenjaminRisk** [comment]
updated QC_Impacts_loopSeeds.sh with the version that is run on the csic cluster. it uses QC_Impacts_Analysis_singleseed_cb.R.
